DROP DATABASE IF EXISTS DartApp;

-- Create DartApp Database
CREATE DATABASE DartApp;
USE DartApp;

-- Player tabel
CREATE TABLE `Player` ( `Id` INT(10) NOT NULL AUTO_INCREMENT , `FullName` VARCHAR(255) NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB; 

-- Match tabel
CREATE TABLE `Match` ( `Id` INT(10) NOT NULL AUTO_INCREMENT , `Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `WinnerId` INT(10) NOT NULL , `SetsToWin` TINYINT(3) NOT NULL , `LegsToWin` TINYINT(3) NOT NULL , `ScoreToWin` SMALLINT(5) NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB; 
ALTER TABLE `Match` ADD CONSTRAINT `MatchWinnerId` FOREIGN KEY (`WinnerId`) REFERENCES `Player`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE; 

-- Participation tabel
CREATE TABLE `Participation` ( `MatchId` INT(10) NOT NULL , `PlayerId` INT(10) NOT NULL , `PlayerIndex` TINYINT(3) NOT NULL , PRIMARY KEY (`MatchId`, `PlayerId`)) ENGINE = InnoDB;

-- Add foreign keys
ALTER TABLE `Participation` ADD CONSTRAINT `ParticipationMatchId` FOREIGN KEY (`MatchId`) REFERENCES `Match`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE; 
ALTER TABLE `Participation` ADD CONSTRAINT `ParticipationPlayerId` FOREIGN KEY (`PlayerId`) REFERENCES `Player`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- Set tabel
CREATE TABLE `Set` ( `Id` INT(10) NOT NULL AUTO_INCREMENT , `Index` TINYINT(3) NOT NULL , `MatchId` INT(10) NOT NULL , `WinnerId` INT(10) NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;

-- Add foreign keys
ALTER TABLE `Set` ADD CONSTRAINT `SetMatchId` FOREIGN KEY (`MatchId`) REFERENCES `Match`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE; 
ALTER TABLE `Set` ADD CONSTRAINT `SetWinnerId` FOREIGN KEY (`WinnerId`) REFERENCES `Player`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- Leg tabel
CREATE TABLE `Leg` ( `Id` INT(10) NOT NULL AUTO_INCREMENT , `Index` TINYINT(3) NOT NULL , `SetId` INT(10) NOT NULL , `WinnerId` INT(10) NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;

-- Add foreign keys
ALTER TABLE `Leg` ADD CONSTRAINT `LegSetId` FOREIGN KEY (`SetId`) REFERENCES `Set`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `Leg` ADD CONSTRAINT `LegWinnerId` FOREIGN KEY (`WinnerId`) REFERENCES `Player`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- Throw tabel
CREATE TABLE `Throw` ( `Id` INT(10) NOT NULL AUTO_INCREMENT , `Index` TINYINT(3) NOT NULL , `TurnId` INT(10) NOT NULL , `ThrownValue` TINYINT(3) NOT NULL , `Kind` TINYINT(3) NOT NULL , `ActualValue` TINYINT(3) NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;

-- Turn tabel
CREATE TABLE `Turn` ( `Id` INT(10) NOT NULL AUTO_INCREMENT , `Index` TINYINT(3) NOT NULL , `LegId` INT(10) NOT NULL , `ThrowerId` INT(10) NOT NULL , `TotalScore` TINYINT(3) NOT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;

-- Add throw foreign key to turn
ALTER TABLE `Throw` ADD CONSTRAINT `ThrowTurnId` FOREIGN KEY (`TurnId`) REFERENCES `Turn`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- Add turn foreign keys to throw
ALTER TABLE `Turn` ADD CONSTRAINT `TurnLegId` FOREIGN KEY (`LegId`) REFERENCES `Leg`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE; 
ALTER TABLE `Turn` ADD CONSTRAINT `TurnThrowerId` FOREIGN KEY (`ThrowerId`) REFERENCES `Throw`(`Id`) ON DELETE CASCADE ON UPDATE CASCADE;